Wizzarts/Web/Wizzarts.Web/Controllers/ExpansionController.cs
namespace Wizzarts.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Wizzarts.Data.Models;
    using Wizzarts.Services.Data;
    using Wizzarts.Web.Infrastructure.Extensions;
    using Wizzarts.Web.ViewModels.Article;
    using Wizzarts.Web.ViewModels.CardGameExpansion;
    using Wizzarts.Web.ViewModels.Event;
    using Wizzarts.Web.ViewModels.Expansion;
    using Wizzarts.Web.ViewModels.PlayCard;

    public class ExpansionController : BaseController
    {
        private readonly IPlayCardService cardService;
        private readonly IDeckService deckService;
        private readonly IPlayCardExpansionService playCardExpansionService;
        private readonly IEventService eventService;
        private readonly IArticleService articleService;
        private readonly UserManager<ApplicationUser> userManager;

        public ExpansionController(
             IPlayCardService cardService,
             IDeckService deckService,
             IPlayCardExpansionService playCardExpansionService,
             IEventService eventService,
             IArticleService articleService,

             UserManager<ApplicationUser> userManager)
        {
            this.cardService = cardService;
            this.deckService = deckService;
            this.playCardExpansionService = playCardExpansionService;
            this.eventService = eventService;
            this.articleService = articleService;
            this.userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> All()
        {
            var viewModel = new ExpansionListViewModel
            {
                CardGameExpansions = await this.playCardExpansionService.GetAll<ExpansionInListViewModel>(),
                Articles = this.articleService.GetRandom<ArticleInListViewModel>(4),
                Events = await this.eventService.GetAll<EventInListViewModel>(),
            };

            return this.View(viewModel);
        }

        [AllowAnonymous]
        public async Task<IActionResult> ById(int id, string information)
        {
            var expansion = await this.playCardExpansionService.GetById<SingleExpansionViewModel>(id);

            if (expansion == null || information != expansion.GetExpansionTitle())
            {
                return this.BadRequest();
            }

            expansion.Cards = await this.cardService.GetAllCardsByExpansion<CardInListViewModel>(id);
            expansion.GameExpansions = await this.playCardExpansionService.GetAll<ExpansionInListViewModel>();

            return this.View(expansion);
        }

        // not used
        public async Task<IActionResult> Order(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            try
            {
                await this.deckService.OrderAsync(id, this.User.GetId());
            }
            catch (Exception ex)
            {
                // return this.RedirectToAction(nameof(this.Add), new { id = id });
            }

            this.TempData["Message"] = "Order added successfully.";

            // TODO: Redirect to article info page
            return this.RedirectToAction("My", "Order");
        }
    }
}

Wizzarts/Web/Wizzarts.Web/Views/Expansion/All.cshtml
@using Wizzarts.Web.Infrastructure.Extensions
@model Wizzarts.Web.ViewModels.CardGameExpansion.ExpansionListViewModel

@{
    this.ViewData["Title"] = "All card game expansions";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row pt-2">
    <div class="col-md-12 col-lg-12 col-xl-9 pl-0 pr-0 pr-xl-1">
        <div class="card">
            <div class="card-body">
                <div class="w-100 span-all mb-5 mt-5">
                    <h4 class="text-center mb-2 ae-border-bottom-light text-header-gold">Wizzarts game expansion</h4>
                    <div id="creatorCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
                        <div class="carousel-inner">
                            @for (var i = 0; i < this.Model.CardGameExpansions.Count(); i++)
                            {
                                if (i == 0)
                                {
                                    <div class="carousel-item active">
                                        <div class="d-flex flex-row justify-content-center featured-creator-cards">

                                            <div class="video-card card border-0">
                                                <div class="yt-img-exp">
                                                    <a asp-controller="Expansion" asp-action="ById" asp-route-id="@this.Model.CardGameExpansions.ToList()[i].Id" asp-route-information="@this.Model.CardGameExpansions.ToList()[i].GetExpansionTitle()">
                                                        <img src="@this.Model.CardGameExpansions.ToList()[i].ExpansionSymbolUrl" alt="@this.Model.CardGameExpansions.ToList()[i].Title" class="lazy" alt="video" style="">

                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <div class="d-flex flex-row justify-content-center featured-creator-cards">

                                            <div class="video-card card border-0">
                                                <div class="yt-img-exp">
                                                    <a asp-controller="Expansion" asp-action="ById" asp-route-id="@this.Model.CardGameExpansions.ToList()[i].Id" asp-route-information="@this.Model.CardGameExpansions.ToList()[i].GetExpansionTitle()">
                                                        <img src="@this.Model.CardGameExpansions.ToList()[i].ExpansionSymbolUrl" alt="@this.Model.CardGameExpansions.ToList()[i].Title" class="lazy" alt="video" style="">
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                        <a class="carousel-control-prev" href="#creatorCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#creatorCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-12 col-xl-3 pl-0 pr-0">
        <div class="card mb-2">
            <div class="w-100 text-center ae-border-bottom-light"><h4><a class="metagroup-link ff-display">Events</a></h4></div>
            <div class="card-body pl-1 pr-1 pt-2 pb-0">
                @foreach (var events in this.Model.Events.Take(4))
                {
                    <div class="metagroup-container">
                        <div class="mr-2 d-none d-lg-block">
                            <a asp-controller="Event" asp-action="ById" asp-route-id="@events.Id" asp-route-information="@events.GetEventTitle()" class="image-wrapper">
                                <img class="meta-cardimg" style="background-image: url('@events.ImageUrl')" alt="">
                            </a>
                        </div>
                        <div>
                            <a asp-controller="Event" asp-action="ById" asp-route-id="@events.Id" asp-route-information="@events.GetEventTitle()" class="image-wrapper">
                                <b class="text-primary">@events.Title</b>
                            </a>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
</div>
<hr />

@section Scripts {
    <script>
        $(document).ready(function () {
            $(function () {
                $('#creatorCarousel .lazy').lazy({
                    appendScroll: $('#lazy-container')
                });
            });
        });
    </script>

}

Wizzarts/Web/Wizzarts.Web/Views/Expansion/ById.cshtml
@model Wizzarts.Web.ViewModels.CardGameExpansion.SingleExpansionViewModel
@using Wizzarts.Web.Infrastructure.Extensions

@{
    this.ViewData["Title"] = "Expansions by Id";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row pt-2">
    <div class="col-md-12 col-lg-12 col-xl-9 pl-0 pr-0 pr-xl-1">
        <div class="card h-oneKpx">
            <div class="row mt-2">
                <div class="col-md-12">
                    <div id="cards" class="outer-container">
                        @if (!Model.Cards.Any())
                        {
                            <div class="d-flex flex-row justify-content-center">
                                <div class="font-weight-bold mt-5" style="max-width: 500px;">
                                    Wizzarts has catalogued every Magic: The Gathering card and token into a comprehensive database. <br>Search through the entire Magic history for additions to your deck, detailed information about ruling, format legalities or different prints of a card.
                                </div>
                            </div>
                        }
                        else
                        {
                            @foreach (var card in this.Model.Cards)
                            {
                                <div class="inner-container">
                                    <div class="item-hidden-text">@card.Name</div>
                                    <a asp-controller="PlayCard" asp-action="ById" asp-route-id="@card.Id" class="item ae-card-link cardLink" data-name="@card.Name" asp-route-information="@card.GetCardName()" data-number="@card.Id" data-img="@card.CardRemoteUrl">
                                        <img class="lazy" src="@card.CardRemoteUrl" alt="@card.Name" style="">
                                    </a>
                                    <div class="item-footer">
                                    </div>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-12 col-xl-3 pl-0 pr-0">
        <div class="card mb-2">
            <div class="w-100 text-center ae-border-bottom-light"><h4><a class="metagroup-link ff-display">Expansions</a></h4></div>
            <div class="card-body pl-1 pr-1 pt-2 pb-0">
                @foreach (var expansion in this.Model.GameExpansions)
                {
                    <div class="metagroup-container">
                        <div class="mr-2 d-none d-lg-block">
                            <a asp-controller="Expansion" asp-action="ById" asp-route-id="@expansion.Id" asp-route-information="@expansion.GetExpansionTitle()" class="image-wrapper">
                                <img class="meta-cardimg-alt" style="background-image: url('@expansion.ExpansionSymbolUrl')" alt="">
                            </a>
                        </div>
                        <div>
                            <a asp-controller="Expansion" asp-action="ById" asp-route-id="@expansion.Id" asp-route-information="@expansion.GetExpansionTitle()"  class="image-wrapper">
                                <b class="text-primary">@expansion.Title</b>
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<hr />