Wizzarts/Web/Wizzarts.Web/Controllers/ArtController.cs
namespace Wizzarts.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Wizzarts.Common;
    using Wizzarts.Data.Models;
    using Wizzarts.Services.Data;
    using Wizzarts.Web.Infrastructure.Extensions;
    using Wizzarts.Web.ViewModels.Art;
    using Wizzarts.Web.ViewModels.Article;
    using Wizzarts.Web.ViewModels.Event;
    using Wizzarts.Web.ViewModels.PlayCard;

    public class ArtController : BaseController
    {
        private readonly IArtService artService;
        private readonly IUserService userService;
        private readonly IArticleService articlesService;
        private readonly IPlayCardService playCardService;
        private readonly IEventService eventService;
        private readonly IWizzartsServices wizzartsServices;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public ArtController(
            IArtService artService,
            IUserService userService,
            IArticleService articlesService,
            IPlayCardService playCardService,
            IEventService eventService,
            IWizzartsServices wizzartsServices,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment)
        {
            this.artService = artService;
            this.userService = userService;
            this.articlesService = articlesService;
            this.playCardService = playCardService;
            this.eventService = eventService;
            this.wizzartsServices = wizzartsServices;
            this.userManager = userManager;
            this.environment = environment;
        }

        public async Task<IActionResult> Add()
        {
            var viewModel = new AddArtViewModel
            {
                Events = await this.eventService.GetAll<EventInListViewModel>(),
            };
            return this.View(viewModel);
        }

        // this will add art. When using add Card (for premium)  and not Create card (mostly events) customer will be redirected to add new ard if he has none
        [HttpPost]
        public async Task<IActionResult> Add(AddArtViewModel input)
        {
            this.ModelState.Remove("UserName");
            this.ModelState.Remove("Password");

            if (await this.artService.ArtTitleExist(input.Title))
            {
                this.ModelState.AddModelError(nameof(input.Title), "Art title exist.");
            }

            if (!this.ModelState.IsValid)
            {
                input.Events = await this.eventService.GetAll<EventInListViewModel>();
                return this.View(input);
            }

            bool isPremium = await this.userService.IsPremium(this.User.GetId());
            try
            {
                await this.artService.AddAsync(input, this.User.GetId(), $"{this.environment.WebRootPath}/images", isPremium);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.Events = await this.eventService.GetAll<EventInListViewModel>();
                return this.View(input);
            }

            this.TempData["Message"] = "Art added successfully.";

            // TODO: Redirect to article info page
            return this.RedirectToAction("MyData", "User");
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (await this.artService.ArtExist(id) == false)
            {
                return this.BadRequest();
            }

            if (await this.artService.HasUserWithIdAsync(id, this.User.GetId()) == false
                && this.User.IsAdmin() == false)
            {
                return this.Unauthorized();
            }

            var inputModel = await this.artService.GetById<EditArtViewModel>(id);

            return this.View(inputModel);
        }

        // avoiding image swap, only title and description can be edited or customer can completely delete it
        [HttpPost]
        public async Task<IActionResult> Edit(EditArtViewModel inputModel, string id)
        {
            if (await this.artService.ArtExist(id) == false)
            {
                return this.BadRequest();
            }

            if (await this.artService.HasUserWithIdAsync(id, this.User.GetId()) == false
                && this.User.IsAdmin() == false)
            {
                return this.Unauthorized();
            }

            this.ModelState.Remove("UserName");
            this.ModelState.Remove("Password");
            this.ModelState.Remove("Image");
            if (await this.artService.ArtTitleExist(inputModel.Title))
            {
                this.ModelState.AddModelError(nameof(inputModel.Title), "Art title exist.");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(inputModel);
            }

            await this.artService.UpdateAsync(inputModel, id);
            return this.RedirectToAction(nameof(this.ById), new { id, information = inputModel.GetInformation() });
        }

        [AllowAnonymous]
        public async Task<IActionResult> All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            var viewModel = new ArtListViewModel
            {
                Arts = this.artService.GetRandom<ArtInListViewModel>(20),
                Articles = this.articlesService.GetRandom<ArticleInListViewModel>(3),
                Events = await this.eventService.GetAll<EventInListViewModel>(),
                Cards = this.playCardService.GetRandom<CardInListViewModel>(3),
            };

            return this.View(viewModel);
        }

        // used for finding all TeamWizzarts art by int id and not string
        public async Task<IActionResult> ByUserId(int id)
        {
            var userId = this.wizzartsServices.GetUserIdByArtistId(id);
            var viewModel = new ArtListViewModel
            {
                Arts = await this.artService.GetAllArtByUserIdPaginationless<ArtInListViewModel>(userId),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(string id, string information)
        {
            if (id == null)
            {
                return this.BadRequest();
            }

            var art = await this.artService.GetById<SingleArtViewModel>(id);
            if (information != art.GetInformation())
            {
                return this.BadRequest();
            }

            art.Events = await this.eventService.GetAll<EventInListViewModel>();
            art.Articles = this.articlesService.GetRandom<ArticleInListViewModel>(3);
            return this.View(art);
        }

        // this has to be approved before it can be used
        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> ApproveArt(string id)
        {
            var userId = await this.artService.ApproveArt(id);
            if (userId != null)
            {
                return this.RedirectToAction("ById", "Member", new { id = $"{userId}", Area = "Administration" });
            }
            else
            {
                return this.BadRequest();
            }
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (await this.artService.ArtExist(id) == false)
            {
                return this.BadRequest();
            }

            if (await this.artService.HasUserWithIdAsync(id, this.User.GetId()) == false
                && this.User.IsAdmin() == false)
            {
                return this.Unauthorized();
            }

            await this.artService.DeleteAsync(id);

            return this.RedirectToAction("MyData", "User");
        }
    }
}

Wizzarts/Web/Wizzarts.Web/Controllers/ArticleController.cs
namespace Wizzarts.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Wizzarts.Common;
    using Wizzarts.Data.Models;
    using Wizzarts.Services.Data;
    using Wizzarts.Web.Infrastructure.Extensions;
    using Wizzarts.Web.ViewModels.Article;

    public class ArticleController : BaseController
    {
        private readonly IArticleService articleService;
        private readonly IUserService userService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment environment;

        public ArticleController(
            IArticleService articleService,
            IUserService userService,
            UserManager<ApplicationUser> userManager,
            IWebHostEnvironment environment)
        {
            this.articleService = articleService;
            this.userService = userService;
            this.userManager = userManager;
            this.environment = environment;
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var article = await this.articleService.GetById<SingleArticleViewModel>(id);
            if (await this.articleService.ArticleExist(id) == false)
            {
                return this.BadRequest();
            }

            if (await this.articleService.HasUserWithIdAsync(id, this.User.GetId()) == false
                && this.User.IsAdmin() == false)
            {
                return this.Unauthorized();
            }
            var viewModel = new EditArticleViewModel();
            viewModel.Title = article.Title;
            viewModel.Description = article.Description;
            viewModel.ShortDescription = article.ShortDescription;
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, EditArticleViewModel input)
        {
            this.ModelState.Remove("UserName");
            this.ModelState.Remove("Password");
            this.ModelState.Remove("ImageUrl");

            var article = await this.articleService.GetById<SingleArticleViewModel>(id);

            if (await this.articleService.ArticleTitleExist(input.Title) && article.Id != id)
            {
                this.ModelState.AddModelError(nameof(input.Title), "Article title exist.");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(input);
            }

            if (await this.articleService.ArticleExist(id) == false)
            {
                return this.BadRequest();
            }

            if (await this.articleService.HasUserWithIdAsync(id, this.User.GetId()) == false
                && this.User.IsAdmin() == false)
            {
                return this.Unauthorized();
            }

            await this.articleService.UpdateAsync(id, input);
            return this.RedirectToAction(nameof(this.ById), new { id, information = input.GetArticleTitle() });
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreateArticleViewModel
            {
                Articles = this.articleService.GetRandom<ArticleInListViewModel>(5),
            };
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateArticleViewModel input)
        {
            this.ModelState.Remove("UserName");
            this.ModelState.Remove("Password");

            if (await this.articleService.ArticleTitleExist(input.Title))
            {
                this.ModelState.AddModelError(nameof(input.Title), "Article title exist.");
            }

            if (!this.ModelState.IsValid)
            {
                input.Articles = this.articleService.GetRandom<ArticleInListViewModel>(5);
                return this.View(input);
            }

            bool isPremium = await this.userService.IsPremium(this.User.GetId());
            try
            {
                await this.articleService.CreateAsync(input, this.User.GetId(), $"{this.environment.WebRootPath}/images", isPremium);
            }
            catch (Exception ex)
            {
                this.ModelState.AddModelError(string.Empty, ex.Message);
                input.Articles = this.articleService.GetRandom<ArticleInListViewModel>(5);
                return this.View(input);
            }

            this.TempData["Message"] = "Article added successfully.";

            return this.RedirectToAction("MyData", "User");
        }

        public async Task<IActionResult> ById(int id, string information)
        {
            var article = await this.articleService.GetById<SingleArticleViewModel>(id);
            if (article == null || information != article.GetArticleTitle())
            {
                return this.BadRequest();
            }

            if (article != null)
            {
                article.Articles = this.articleService.GetRandom<ArticleInListViewModel>(3);
            }

            return this.View(article);
        }

        [HttpPost]
        [Authorize(Roles = GlobalConstants.AdministratorRoleName)]
        public async Task<IActionResult> ApproveArticle(int id)
        {
            var userId = await this.articleService.ApproveArticle(id);
            if (userId != null)
            {
                return this.RedirectToAction("ById", "Member", new { id = $"{userId}", Area = "Administration" });
            }
            else
            {
                return this.BadRequest();
            }
        }

        // this has to be approved before it can be used
        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (await this.articleService.ArticleExist(id) == false)
            {
                return this.BadRequest();
            }

            if (await this.articleService.HasUserWithIdAsync(id, this.User.GetId()) == false
                && this.User.IsAdmin() == false)
            {
                return this.Unauthorized();
            }

            await this.articleService.DeleteAsync(id);

            return this.RedirectToAction("MyData", "User");
        }

        public async Task<IActionResult> All()
        {
            var viewModel = new ArticleListViewModel()
            {
                Articles = this.articleService.GetRandom<ArticleInListViewModel>(4),
                UserArticles = await this.articleService.GetAllUserArticles<ArticleInListViewModel>(),
            };

            return this.View(viewModel);
        }
    }
}

Wizzarts/Web/Wizzarts.Web/Views/PlayCard/All.cshtml
@model Wizzarts.Web.ViewModels.PlayCard.CardListViewModel
@using Wizzarts.Web.Infrastructure.Extensions
@{
    this.ViewData["Title"] = "All play cards";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row pt-2">
    <div class="col-md-12 col-lg-12 col-xl-9 pl-0 pr-0 pr-xl-1">
        <div class="card">
            <div class="card-body">
                <div class="w-100 span-all mb-5 mt-5">
                    <h4 class="text-center mb-2 ae-border-bottom-light text-header-gold">Wizzarts Art</h4>
                    <div id="creatorCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
                        <div class="carousel-inner">

                            @for (var i = 0; i < this.Model.Cards.Where(x => x.ApprovedByAdmin == true && x.IsEventCard == false).Count(); i++)
                            {
                                if (i == 0)
                                {
                                    <div class="carousel-item active">
                                        <div class="d-flex flex-row justify-content-center featured-creator-cards">

                                            <div class="video-card-cards card border-0">
                                                <div class="yt-img">
                                                    <a asp-controller="PlayCard" asp-action="ById" asp-route-id="@this.Model.Cards.ToList()[i].Id" asp-route-information="@this.Model.Cards.ToList()[i].GetCardName()">
                                                        <img src="@this.Model.Cards.ToList()[i].CardRemoteUrl" alt="@this.Model.Cards.ToList()[i].Name" class="lazy" alt="video" style="">

                                                    </a>
                                                </div>
                                                <div class="article-card card border-0">
                                                    <div class="card-body pt-0">
                                                        <div class="ff-display font-size-18">
                                                            <b>@this.Model.Cards.ToList()[i].Name</b>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="carousel-item">
                                        <div class="d-flex flex-row justify-content-center featured-creator-cards">

                                            <div class="video-card-cards card border-0">
                                                <div class="yt-img">
                                                    <a asp-controller="PlayCard" asp-action="ById" asp-route-id="@this.Model.Cards.ToList()[i].Id" asp-route-information="@this.Model.Cards.ToList()[i].GetCardName()">
                                                        <img src="@this.Model.Cards.ToList()[i].CardRemoteUrl" alt="@this.Model.Cards.ToList()[i].Name" class="lazy" alt="video" style="">
                                                    </a>
                                                </div>
                                                <div class="article-card card border-0">
                                                    <div class="card-body pt-0">
                                                        <div class="ff-display font-size-18">
                                                            <b>@this.Model.Cards.ToList()[i].Name</b>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }

                            }
                        </div>
                        <a class="carousel-control-prev" href="#creatorCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#creatorCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-md-12 col-lg-12 col-xl-3 pl-0 pr-0">
        <div class="card mb-2">
            <div class="w-100 text-center ae-border-bottom-light"><h4><a class="metagroup-link ff-display">Events</a></h4></div>
            <div class="card-body pl-1 pr-1 pt-2 pb-0">
                @foreach (var events in this.Model.Events.Take(5))
                {
                    <div class="metagroup-container">
                        <div class="mr-2 d-none d-lg-block">
                            <a asp-controller="Event" asp-action="ById" asp-route-id="@events.Id" asp-route-information="@events.GetEventTitle()" class="image-wrapper">
                                <div class="meta-cardimg" style="background-image: url('@events.ImageUrl')"></div>
                            </a>
                        </div>
                        <div>
                            <a asp-controller="Event" asp-action="ById" asp-route-id="@events.Id" asp-route-information="@events.GetEventTitle()" class="image-wrapper">
                                <b class="text-primary">@events.Title</b>
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="card mb-2">
            <div class="w-100 text-center ae-border-bottom-light"><h4><a class="metagroup-link ff-display">Articles</a></h4></div>
            <div class="card-body pl-1 pr-1 pt-2 pb-0">
                @foreach (var article in this.Model.Articles.Take(3))
                {
                    <div class="metagroup-container">
                        <div class="mr-2 d-none d-lg-block">
                            <a asp-controller="Article" asp-action="ById" asp-route-id="@article.Id" asp-route-information="@article.GetArticleTitle()" class="image-wrapper">
                                <div class="meta-cardimg" style="background-image: url('@article.ImageUrl')"></div>
                            </a>
                        </div>
                        <div>
                            <a asp-controller="Article" asp-action="ById" asp-route-id="@article.Id" asp-route-information="@article.GetArticleTitle()" class="image-wrapper">
                                <b class="text-primary">@article.Title</b>
                            </a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<hr />

Wizzarts/Web/Wizzarts.Web/Views/PlayCard/_CreateCardWithArtInputPartial.cshtml
@model Wizzarts.Web.ViewModels.PlayCard.CreateCardViewModel

@if (Model.ArtByUserId.Any(x => x.ApprovedByAdmin == true))
{
    <form method="post" id="cardinfo" enctype="multipart/form-data">
        <table border="0" cellspacing="0" cellpadding="2" style="width:100%;">
            <tbody>
                <tr id="artByArtistV2" class="row1">
                    <td>
                        <label asp-for="ArtId">Art:</label>
                    </td>
                    <td>
                        <select asp-for="ArtId" id="artByArtist" onchange="artByArtistFunc(event);">
                            <option value="1" selected="true" hidden>
                            </option>
                            @foreach (var art in Model.ArtByUserId)
                            {
                                <option data-container="@art.ImageUrl" value="@art.Id">@art.Title</option>
                            }
                        </select>
                    </td>
                    <span asp-validation-for="@Model.ArtId" class="small text-danger"></span>
                </tr>
                <div class="form-group row mb-1" hidden>
                    <label class="col-sm-2 col-lg-2 col-form-label" asp-for="@Model.Images"></label>
                    <div class="col-sm-8 col-lg-6">
                        <input asp-for="@Model.Images" type="hidden" value="" name="canvasCapture" class="form-control" id="imageData">
                    </div>
                </div>
                <tr id="cardTypeV2" class="row1">
                    <td>
                        <label asp-for="CardTypeId">Type:</label>
                    </td>
                    <td>
                        <select asp-for="CardTypeId" id="newtype" onchange="cardTypeFunc(event)">

                            @foreach (var type in Model.SelectType)
                            {
                                <option value="@type.Id">@type.Name</option>
                            }
                        </select>
                    </td>
                    <span asp-validation-for="@Model.CardTypeId" class="small text-danger"></span>
                </tr>
                <tr class="row2" hidden>
                    <td>
                        <label asp-for="GameExpansionId">Expansion Symbol:</label>
                    </td>
                    <td>
                        <select asp-for="GameExpansionId" id="expansion" onchange="expansionSymbolFunc(event)">
                            <option value="3" selected="true">
                            </option>
                            @foreach (var type in Model.SelectExpansion)
                            {
                                <option value="@type.Id">@type.Title</option>
                            }
                        </select>
                    </td>
                    <span asp-validation-for="@Model.GameExpansionId" class="small text-danger"></span>
                </tr>

                <input type="submit" id="submitEventTwo" value="Submit" class="btn btn-warning" hidden>
            </tbody>
        </table>

    </form>

    <table border="0" cellspacing="0" cellpadding="2" style="width:100%;">
        <tbody>

            <tr class="row1">
                <td>
                    <div id="previewEventTwo" style="font-size:16px;min-width:0px">
                        <button class="btn btn-info">Preview</button>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
}
else
{
    @if (Model.ArtByUserId.Any())
    {
        <div class="row text-center no-gutters">
            <div class="col-md-12">
                <h2 class="text-header-gold">You have @Model.ArtByUserId.Count() art piece(s) waiting for approval.Click below to add new art piece.</h2>
                <p>
                    <a class="dropdown-item" asp-area="" asp-controller="Art" asp-action="Add"><i class="fa fa-picture-o" aria-hidden="true"></i> <b>Create Art</b></a>
                </p>
            </div>
        </div>
    }
    else
    {
        <div class="row text-center no-gutters">
            <div class="col-md-12">
                <h2 class="text-header-gold">You do not own any art. Click below to add a new art piece</h2>
                <p>
                    <a class="dropdown-item" asp-area="" asp-controller="Art" asp-action="Add"><i class="fa fa-picture-o" aria-hidden="true"></i> <b>Create Art</b></a>
                </p>
            </div>
        </div>
    }
}

Wizzarts/Web/Wizzarts.Web/Views/PlayCard/_OutputFromCreateCardPartialsPartial.cshtml
@model Wizzarts.Web.ViewModels.PlayCard.CreateCardViewModel
@using static Wizzarts.Common.HardCodedConstants;

<div class="col-md-12 col-lg-12 col-xl-3 pl-0 pr-0">
    <div class="second" id="second">
        @if (Model.EventCategoryId == FlavorlessType)
        {
            <div id="card-container" class="card-container">
                <div class="card-background" id="background" style="background-image: url('@Model.CardFrameDefaultUrl')">
                    <div class="card-frame">
                        <div class="frame-header">
                            <div class="name">
                                <p id="cardName">
                                    @Model.CardDefaultName
                                </p>
                            </div>
                            <div id="imgHeader" class="card-imageframe">
                            </div>

                        </div>
                        <img class="frame-art" src="@Model.EventMilestoneImage" alt="Nature">

                        <div class="frame-type-line" id="frame-type-line">
                            <h1 class="type" id="cardtype">@Model.CardDefaultType </h1>
                            <div id="symbolHeader">
                                <img src="@Model.CardExpansionSymbolDefaultUrl" alt=""/>
                            </div>
                        </div>
                        <div class="frame-text-box">
                            <div class="description" id="description">
                                <p>
                                    @Model.EventDescription
                                </p>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="frame-bottom-info inner-margin">
                    <div class="fbi-left">
                    </div>
                    <div class="fbi-center"></div>
                    <div class="fbi-right">
                    </div>
                </div>
                <div class="container-power" id="container-power">
                    <img id="power-frame" src="~/images/frames/whiteValue.png" alt="Nature">
                    <div class="centered-power"></div>
                </div>
            </div>

        }
        @if (Model.EventCategoryId == ImagelessType)
        {
            <div id="card-container" class="card-container">
                <div class="card-background" id="backgroundTwo" style="background-image: url('@Model.EventMilestoneImage')">
                    <div class="card-frame">
                        <div id="imageInput" class="frame-art-v2">
                        </div>
                    </div>
                    <div class="frame-header-v2">
                        <div class="symbolFrame" id="symbolHeader">
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>